server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /items {
        proxy_pass http://gateway;
    }

    location /auth/login {
        proxy_pass http://gateway;
    }

    location /auth/register {
        proxy_pass http://gateway;
    }

    location /users {
       proxy_pass http://gateway;
    }
}
