version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/server"
      target-branch: "main"
      rebase-strategy: "disabled"
      schedule:
        interval: "weekly"
        day: "monday"
        time: "03:00"
        timezone: "Europe/Paris"

    - package-ecosystem: "npm"
      directory: "/client"
      target-branch: "main"
      rebase-strategy: "disabled"
      schedule:
        interval: "weekly"
        day: "monday"
        time: "03:00"
        timezone: "Europe/Paris"

    - package-ecosystem: "docker"
      directory: "/"
      target-branch: "main"
      rebase-strategy: "disabled"
      schedule:
        interval: "weekly"
        day: "monday"
        time: "03:00"
        timezone: "Europe/Paris"

    - package-ecosystem: "github-actions"
      directory: "/"
      target-branch: "main"
      rebase-strategy: "disabled"
      schedule:
        interval: "weekly"
        day: "monday"
        time: "03:00"
        timezone: "Europe/Paris"
