services:
  db:
    image: mysql:8
    env_file:
      - ./server/.env.docker
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '8025:8025' # web UI
      - '1025:1025' # SMTP
    
  auth-service:
    build: ./server
    env_file:
     - ./server/.env.docker
    command: ["node", "dist/apps/auth-service/src/index.js"]
    depends_on:
      db:
        condition: service_healthy
  
  project-service:
    build: ./server
    env_file:
      - ./server/.env.docker
    command: ["node", "dist/apps/project-service/src/index.js"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  
  task-service:
    build: ./server
    env_file:
      - ./server/.env.docker
    command: ["node", "dist/apps/task-service/src/index.js"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  notification-service:
    build: ./server
    env_file:
      - ./server/.env.docker
    command: ["node", "dist/apps/notification-service/src/index.js"]
    depends_on:
      redis:
        condition: service_started
      mailpit:
        condition: service_started

  gateway:
    build: ./server
    env_file:
      - ./server/.env.docker
    command: ["node", "dist/apps/gateway/index.js"]
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - project-service
      - task-service
      - notification-service

  client:
    build:
      context: ./client
      args:
        VITE_API_URL: /api
    ports:
      - "80:80"
    depends_on:
      - gateway


volumes:
  db_data:
