server {
    listen 80;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    location /items {
        proxy_pass http://server:3000;
    }

    
    location /auth/login {
        proxy_pass http://server:3000;
    }

    location /auth/register {
        proxy_pass http://server:3000;
    }

    location /users {
        proxy_pass http://server:3000;
    }
}
