import test from 'node:test';
import assert from 'node:assert/strict';
import { assertDependabotSkipGuard, readText, readYaml } from './helpers.mjs';

test('protected main push workflow verifies, pushes, then publishes integration manifest', () => {
  const workflow = readYaml('.github/workflows/pre_push_main.yml');
  const workflowContent = readText('.github/workflows/pre_push_main.yml');
  const planWorkflow = readYaml('.github/workflows/_main-plan.yml');
  const versionWorkflow = readYaml('.github/workflows/_main-version-packages.yml');
  const verifyWorkflow = readYaml('.github/workflows/_main-verify-image.yml');
  const pushWorkflow = readYaml('.github/workflows/_main-push-image.yml');
  const manifestWorkflow = readYaml('.github/workflows/_main-publish-manifest.yml');
  const finalTagsWorkflow = readYaml('.github/workflows/_main-finalize-tags.yml');
  const { plan } = workflow.jobs;
  const verify = workflow.jobs['verify-images'];
  const push = workflow.jobs['push-images'];
  const update = workflow.jobs['update-integration'];
  const finalize = workflow.jobs['finalize-image-tags'];
  const dispatch = workflow.jobs['dispatch-integration-deploy'];
  const versionPackages = workflow.jobs['version-packages'];
  const planJob = planWorkflow.jobs.plan;
  const versionJob = versionWorkflow.jobs.version;
  const verifyJob = verifyWorkflow.jobs.verify;
  const pushJob = pushWorkflow.jobs.push;
  const manifestJob = manifestWorkflow.jobs.publish;
  const finalTagsJob = finalTagsWorkflow.jobs.finalize;
  const planCheckout = planJob.steps.find((step) => step.name === 'Checkout');
  const planStep = planJob.steps.find((step) => step.id === 'plan');
  const releaseVersionStep = planJob.steps.find((step) => step.name === 'Validate integration release versions');
  const versionTokenStep = versionJob.steps.find((step) => step.name === 'Generate CD app token');
  const versionCheckout = versionJob.steps.find((step) => step.name === 'Checkout');
  const commitVersionStep = versionJob.steps.find((step) => step.name === 'Commit version package artifacts');
  const verifyCheckout = verifyJob.steps.find((step) => step.name === 'Checkout');
  const updateTokenStep = manifestJob.steps.find((step) => step.name === 'Generate CD app token');
  const updateCheckout = manifestJob.steps.find((step) => step.name === 'Checkout');
  const verifyImageStep = verifyJob.steps.find((step) => step.id === 'image');
  const smokeStep = verifyJob.steps.find((step) => step.id === 'smoke');
  const trivyStep = verifyJob.steps.find((step) => step.id === 'trivy');
  const saveImageStep = verifyJob.steps.find((step) => step.id === 'save_image');
  const pushCandidateStep = pushJob.steps.find((step) => step.id === 'push_candidate');
  const createManifestStep = manifestJob.steps.find((step) => step.name === 'Create versioned deployment manifest');
  const commitManifestStep = manifestJob.steps.find((step) => step.name === 'Commit deployment manifest');
  const publishResultStep = manifestJob.steps.find((step) => step.id === 'publish_result');
  const finalTagsStep = finalTagsJob.steps.find((step) => step.id === 'final_tags');
  const dispatchStep = dispatch.steps.find((step) => step.name === 'Dispatch Deploy Integration workflow');

  assert.deepEqual(workflow.on.push.branches, ['main']);
  assert.equal(workflow.on.pull_request_target, undefined);
  assertDependabotSkipGuard(assert, plan.if);
  assertDependabotSkipGuard(assert, versionPackages.if);
  assert.equal(versionPackages.uses, './.github/workflows/_main-version-packages.yml');
  assert.equal(plan.uses, './.github/workflows/_main-plan.yml');
  assert.equal(verify.uses, './.github/workflows/_main-verify-image.yml');
  assert.equal(push.uses, './.github/workflows/_main-push-image.yml');
  assert.equal(update.uses, './.github/workflows/_main-publish-manifest.yml');
  assert.equal(finalize.uses, './.github/workflows/_main-finalize-tags.yml');
  assert.equal(planCheckout.with.ref, '${{ inputs.source_revision }}');
  assert.equal(planStep.with.base, '${{ steps.revisions.outputs.base }}');
  assert.equal(planStep.with.head, '${{ steps.revisions.outputs.head }}');
  assert.match(releaseVersionStep.run, /integration-release-plan\.mjs/);
  assert.match(releaseVersionStep.run, /--manifest latest/);
  assert.equal(versionJob.permissions.contents, 'write');
  assert.equal(versionTokenStep.uses, 'actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1');
  assert.equal(versionTokenStep.with['private-key'], '${{ secrets.cd_app_private_key }}');
  assert.equal(versionCheckout.with.token, '${{ steps.cd-app-token.outputs.token }}');
  assert.match(commitVersionStep.run, /git push origin HEAD:main/);
  assert.equal(verify.if, "${{ needs.plan.outputs.service_count != '0' }}");
  assert.equal(verifyJob.strategy.matrix, '${{ fromJson(inputs.service_matrix) }}');
  assert.equal(verifyJob.strategy['max-parallel'], undefined);
  assert.equal(verifyCheckout.with.ref, '${{ inputs.source_revision }}');
  assert.equal(verifyImageStep.uses, './.github/actions/build-service-image');
  assert.equal(verifyImageStep.with['tag-mode'], 'candidate');
  assert.equal(verifyImageStep.with.push, 'false');
  assert.equal(verifyImageStep.with.load, 'true');
  assert.match(smokeStep.run, /--add-host gateway:127\.0\.0\.1/);
  assert.equal(trivyStep.with['image-ref'], '${{ steps.image.outputs.candidate_ref }}');
  assert.match(saveImageStep.run, /docker save/);
  assert.deepEqual(push.needs, ['version-packages', 'plan', 'verify-images']);
  assert.match(push.if, /needs\.verify-images\.result == 'success'/);
  assert.equal(pushJob.strategy.matrix, '${{ fromJson(inputs.service_matrix) }}');
  assert.match(pushCandidateStep.run, /docker load/);
  assert.match(pushCandidateStep.run, /docker push "\$candidate_ref"/);
  assert.match(pushCandidateStep.run, /release-metadata\/metadata\.json/);
  assert.deepEqual(update.needs, ['version-packages', 'plan', 'push-images']);
  assert.equal(manifestJob.outputs.manifest_published, '${{ steps.publish_result.outputs.published }}');
  assert.equal(updateTokenStep.with['private-key'], '${{ secrets.cd_app_private_key }}');
  assert.equal(updateCheckout.with.token, '${{ steps.cd-app-token.outputs.token }}');
  assert.match(createManifestStep.run, /manifest\.mjs create-version/);
  assert.match(commitManifestStep.run, /git push origin HEAD:main/);
  assert.match(publishResultStep.run, /published=true/);
  assert.deepEqual(finalize.needs, ['version-packages', 'plan', 'push-images', 'update-integration']);
  assert.match(finalize.if, /manifest_published == 'true'/);
  assert.match(finalTagsStep.run, /imagetools create/);
  assert.match(finalTagsStep.run, /Version tag .* already points/);
  assert.deepEqual(dispatch.needs, ['plan', 'update-integration', 'finalize-image-tags']);
  assert.match(dispatchStep.run, /gh workflow run deploy-integration\.yml/);
  assert.doesNotMatch(workflowContent, /peter-evans\/create-pull-request/);
  assert.doesNotMatch(workflowContent, /CD_PUSH_TOKEN|VERSION_PR_TOKEN|MANIFEST_UPDATE_TOKEN/);
  assert.doesNotMatch(workflowContent, /needs\.verify-images\.result != 'success'[\s\S]*docker push/);
});
