name: Hadolint

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/Dockerfile"

jobs:
  hadolint:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Lint client Dockerfile
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf
        with:
          dockerfile: client/Dockerfile

      - name: Lint auth-service Dockerfile
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf
        with:
          dockerfile: server/apps/auth-service/Dockerfile

      - name: Lint gateway Dockerfile
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf
        with:
          dockerfile: server/apps/gateway/Dockerfile

      - name: Lint notification-service Dockerfile
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf
        with:
          dockerfile: server/apps/notification-service/Dockerfile

      - name: Lint project-service Dockerfile
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf
        with:
          dockerfile: server/apps/project-service/Dockerfile

      - name: Lint task-service Dockerfile
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf
        with:
          dockerfile: server/apps/task-service/Dockerfile
